### ISSUE TITLE
[Suggestion] Log Example on the front page

### ISSUE THREAD

**Issue by jbruett** [platta/PSMultiLog#1]
Adam, 

Quick suggestion...add an example of a log file/email/windows event to the readme.md file here for folks to see what a log event looks like.

**Comment by platta** [comment]
Great suggestion. Thanks!

**Comment by platta** [comment]
Whoops, didn't mean to close the issue. I still have to add the other examples.

**Comment by platta** [comment]
Using this space to upload images so I can reference them from README.md

![emaillog](https://cloud.githubusercontent.com/assets/946913/10434409/5542458e-70e7-11e5-97a7-bdf6d114d179.PNG)
![eventlogerror](https://cloud.githubusercontent.com/assets/946913/10434411/55444140-70e7-11e5-8dc8-a104ec2f09a4.PNG)
![eventlogerrorexception](https://cloud.githubusercontent.com/assets/946913/10434410/5542f72c-70e7-11e5-8473-79cc6048d7f4.PNG)
![eventloginfo](https://cloud.githubusercontent.com/assets/946913/10434412/55451840-70e7-11e5-863e-de06a39ae24d.PNG)
![eventlogwarning](https://cloud.githubusercontent.com/assets/946913/10434413/55458ba4-70e7-11e5-9612-59a5e9c573c6.PNG)
![hostlog](https://cloud.githubusercontent.com/assets/946913/10434414/554666e6-70e7-11e5-99f4-601ab9218a02.PNG)
